os: linux
dist: xenial
language: python
python:
  - "3.6"
  - "3.7"
install:
  - pip install -r requirements.txt
  - pip install flake8
  - pip install pylint
script:
  - python setup.py test
  - make lint
